# Generated by Django 4.0 on 2022-01-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='feeds',
            field=models.CharField(blank=True, max_length=250, verbose_name='feeds'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=250, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='company',
            name='url_corp',
            field=models.CharField(blank=True, max_length=250, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipCode',
            field=models.CharField(blank=True, max_length=100, verbose_name='zipCode'),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='description',
            field=models.TextField(max_length=999, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='presentation',
            field=models.CharField(choices=[('gram', 'Gram'), ('unit', 'Unit'), ('milliliter', 'Milliliter'), ('kilogram', 'Kilogram')], default='gram', max_length=50, verbose_name='presentation'),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('protein', 'Protein'), ('fruVer', 'FruVer')], default='grocery', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalreceta',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalreceta',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(max_length=999, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='presentation',
            field=models.CharField(choices=[('gram', 'Gram'), ('unit', 'Unit'), ('milliliter', 'Milliliter'), ('kilogram', 'Kilogram')], default='gram', max_length=50, verbose_name='presentation'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('protein', 'Protein'), ('fruVer', 'FruVer')], default='grocery', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='feeds',
            field=models.CharField(blank=True, max_length=250, verbose_name='feeds'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=250, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url_corp',
            field=models.CharField(blank=True, max_length=250, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='feeds',
            field=models.CharField(blank=True, max_length=250, verbose_name='feeds'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=250, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url_corp',
            field=models.CharField(blank=True, max_length=250, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zipCode',
            field=models.CharField(blank=True, max_length=100, verbose_name='zipCode'),
        ),
    ]
